# Generated by Django 2.1.7 on 2019-03-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190309_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.TextField(blank=True),
        ),
    ]
