# Generated by Django 2.1.7 on 2019-03-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='my_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
