# Generated by Django 2.1.7 on 2019-03-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190310_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='my_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.TextField(blank=True, default='a'),
            preserve_default=False,
        ),
    ]
