# Generated by Django 2.1.7 on 2019-03-12 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190311_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'moderators'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
