# Generated by Django 2.1.7 on 2019-03-12 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190312_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Moderators'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
