# Generated by Django 2.1.7 on 2019-03-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190312_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Product approved by moderators'),
        ),
        migrations.AddField(
            model_name='product',
            name='mod_review',
            field=models.TextField(blank=True, null=True, verbose_name='Review sent by moderator'),
        ),
    ]
