# Generated by Django 2.1.7 on 2019-03-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190312_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewed_by_mod',
            field=models.BooleanField(blank=True, default=False, verbose_name='Was product reviewed by Moderator'),
        ),
    ]
